### PR TITLE
UM890 Pro

### PR DESCRIPTION
**Pull request by dextouu**
Hello, I managed to get the graphics card working on Windows 11 including the audio. on windows 10, the graphics card gives me an error 43 on the graphics card.
I added like 2 PCI ports, the third 3 is useless, I removed it.
I added a capture below, to show in image.
Capture d'écran 2024-09-25 192317

I also added the latest pack to extract the bios.bin (ubu), otherwise the extraction will not work on the latest models.
I would also advise, for beginners or not, especially to add the "panic=10" parameter to grub, in case proxmox crashes, to avoid sudden shutdowns.

### CODE REVIEW

**Comment by isc30** [comment]
Awesome thanks!

**Comment by FabioEight** [comment]
Hello @dextouu , world you mind sharing your VM conf? Mi facing issues while booting W11, its crashing just after the bootloader. Thanks!

**Comment by dextouu** [comment]
> Hello @dextouu , world you mind sharing your VM conf? Mi facing issues while booting W11, its crashing just after the bootloader. Thanks!


>  ```
agent: 1
args: -cpu 'host,-hypervisor,kvm=off,vendor=AuthenticAMD'
balloon: 0
bios: ovmf
boot: order=ide0;ide2;net0
cores: 8
cpu: host
hostpci0: 0000:c5:00.0,pcie=1,romfile=vbios_8945.bin,x-vga=1
hostpci1: 0000:c5:00.1,pcie=1,romfile=AMDGopDriver.rom
hostpci2: 0000:c5:00.6,pcie=1
efidisk0: local-lvm:vm-100-disk-0,efitype=4m,pre-enrolled-keys=1,size=4M
ide0: local-lvm:vm-100-disk-1,backup=0,discard=on,size=80G
ide2: local:iso/fr-fr_windows_11_consumer_editions_version_23h2_x64_dvd_00e>
machine: pc-q35-8.0
memory: 20048
meta: creation-qemu=9.0.2,ctime=1726912322
name: windows11
net0: virtio=BC:24:11:42:FC:2B,bridge=vmbr0,firewall=1
numa: 0
ostype: win11
scsihw: virtio-scsi-single
smbios1: uuid=091c9a50-06a7-494e-ae39-c766355ea0a9
sockets: 1
tpmstate0: local-lvm:vm-100-disk-2,size=4M,version=v2.0
vga: virtio
```

**Comment by FabioEight** [comment]
> > Hello @dextouu , world you mind sharing your VM conf? Mi facing issues while booting W11, its crashing just after the bootloader. Thanks!
> 
> > Are you just crashing the VM or the host system, with a Panic kernel?
> 
> ```
> agent: 1
> args: -cpu 'host,-hypervisor,kvm=off,vendor=AuthenticAMD'
> balloon: 0
> bios: ovmf
> boot: order=ide0;ide2;net0
> cores: 8
> cpu: host
> hostpci0: 0000:c5:00.0,pcie=1,romfile=vbios_8945.bin,x-vga=1
> hostpci1: 0000:c5:00.1,pcie=1,romfile=AMDGopDriver.rom
> hostpci2: 0000:c5:00.6,pcie=1
> efidisk0: local-lvm:vm-100-disk-0,efitype=4m,pre-enrolled-keys=1,size=4M
> ide0: local-lvm:vm-100-disk-1,backup=0,discard=on,size=80G
> ide2: local:iso/fr-fr_windows_11_consumer_editions_version_23h2_x64_dvd_00e>
> machine: pc-q35-8.0
> memory: 20048
> meta: creation-qemu=9.0.2,ctime=1726912322
> name: windows11
> net0: virtio=BC:24:11:42:FC:2B,bridge=vmbr0,firewall=1
> numa: 0
> ostype: win11
> scsihw: virtio-scsi-single
> smbios1: uuid=091c9a50-06a7-494e-ae39-c766355ea0a9
> sockets: 1
> tpmstate0: local-lvm:vm-100-disk-2,size=4M,version=v2.0
> vga: virtio
> ```

I'll try to replicate your config.
The host crash when I run Windows VM (configured as the main tutorial). Doesn't seem a kernel crash according to journalctl, however I have to physically reboot the host.

**Comment by dextouu** [comment]
Adds to grub as parameter: panic=10, for GRUB restarts after a Panic kernel. Do you have the same config as me, ? I have a dummy hdmi dongle to simulate a screen plugged into the screen. The screen should not be left on while using the vm, why the hdmi is used by the vm.
For the sound, you have to add the two lines otherwise it crashes. I have already tried on my side.

**Comment by dextouu** [comment]
Adds to grub as parameter: panic=10, for GRUB restarts after a Panic kernel. Do you have the same config as me, ? I have a dummy hdmi dongle to simulate a screen plugged into the screen. The screen should not be left on while using the vm, why the hdmi is used by the vm.
For the sound, you have to add the two lines otherwise it crashes. I have already tried on my side.

**Comment by FabioEight** [comment]
> Adds to grub as parameter: panic=10, for GRUB restarts after a Panic kernel. Do you have the same config as me, ? I have a dummy hdmi dongle to simulate a screen plugged into the screen. The screen should not be left on while using the vm, why the igpu is used by the vm. For the sound, you have to add the two lines otherwise it crashes. I have already tried on my side.

I have a monitor connected to UM890 Pro. By adding the third device c6:00.6 (c5 in your setup), I was able to boot and the driver got installed via Windows Update. However, I’m now facing a BSOD loop with error 0xc00007b..
I’ll consider to install a new Windows instance, as this one was not brand new.

**Comment by FabioEight** [comment]
@dextouu so I did a fresh install of Windows 11. I was able to configure the passthrough and install the Radeon driver.
However, following the reboot required to complete the driver installation, I have no longer access to the Windows 11 machine. No physical output, no output on console. I think the machine is crashing immediately as I have to perform a reset via Proxmox.
Below my configuration snippet
```
hostpci0: 0000:c6:00.0,pcie=1,romfile=vbios_8945.bin,x-vga=1
hostpci1: 0000:c6:00.1,pcie=1,romfile=AMDGopDriver_8945.rom
hostpci2: 0000:c6:00.6,pcie=1
```
Please note the c6 addresses are correct.
Would you mind sharing your `/etc/modprobe.d/vfio.conf`?
My current is:

```
options vfio-pci ids=1002:1900,1002:1640
softdep radeon pre: vfio-pci
softdep amdgpu pre: vfio-pci
softdep snd_hda_intel pre: vfio-pci
```
Maybe I have to try to add 1022:15e3 as well?

```
c6:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix3 [1002:1900] (rev c4)
	Subsystem: Device [1f4c:b016]
	Kernel driver in use: vfio-pci
	Kernel modules: amdgpu
c6:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt Radeon High Definition Audio Controller [1002:1640]
	Subsystem: Device [1f4c:b016]
	Kernel driver in use: vfio-pci
	Kernel modules: snd_hda_intel
c6:00.2 Encryption controller [1080]: Advanced Micro Devices, Inc. [AMD] Family 19h (Model 74h) CCP/PSP 3.0 Device [1022:15c7]
	Subsystem: Device [1f4c:b016]
	Kernel driver in use: ccp
	Kernel modules: ccp
c6:00.3 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Device [1022:15b9]
	Subsystem: Device [1f4c:b016]
	Kernel driver in use: xhci_hcd
	Kernel modules: xhci_pci
c6:00.4 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Device [1022:15ba]
	Subsystem: Device [1f4c:b016]
	Kernel driver in use: xhci_hcd
	Kernel modules: xhci_pci
c6:00.5 Multimedia controller [0480]: Advanced Micro Devices, Inc. [AMD] ACP/ACP3X/ACP6x Audio Coprocessor [1022:15e2] (rev 63)
	Subsystem: Device [1f4c:b016]
	Kernel driver in use: vfio-pci
	Kernel modules: snd_pci_acp3x, snd_rn_pci_acp3x, snd_pci_acp5x, snd_pci_acp6x, snd_acp_pci, snd_rpl_pci_acp6x, snd_pci_ps, snd_sof_amd_renoir, snd_sof_amd_rembrandt, snd_sof_amd_vangogh, snd_sof_amd_acp63
c6:00.6 Audio device [0403]: Advanced Micro Devices, Inc. [AMD] Family 17h/19h HD Audio Controller [1022:15e3]
	DeviceName: Realtek ALC256
	Subsystem: Device [1f4c:b016]
	Kernel driver in use: vfio-pci
	Kernel modules: snd_hda_intel
```

**Comment by FabioEight** [comment]
Update:

I was able to passthrough everything and get physical output, I had to add those devices as well:
```
c6:00.5 Multimedia controller [0480]: Advanced Micro Devices, Inc. [AMD] ACP/ACP3X/ACP6x Audio Coprocessor [1022:15e2] (rev 63)
	Subsystem: Device [1f4c:b016]
	Kernel driver in use: vfio-pci
	Kernel modules: snd_pci_acp3x, snd_rn_pci_acp3x, snd_pci_acp5x, snd_pci_acp6x, snd_acp_pci, snd_rpl_pci_acp6x, snd_pci_ps, snd_sof_amd_renoir, snd_sof_amd_rembrandt, snd_sof_amd_vangogh, snd_sof_amd_acp63
c6:00.6 Audio device [0403]: Advanced Micro Devices, Inc. [AMD] Family 17h/19h HD Audio Controller [1022:15e3]
	DeviceName: Realtek ALC256
	Subsystem: Device [1f4c:b016]
	Kernel driver in use: vfio-pci
	Kernel modules: snd_hda_intel
```

Current config:

```
hostpci0: 0000:c6:00.0,pcie=1,romfile=vbios_8945.bin,x-vga=1
hostpci1: 0000:c6:00.1,pcie=1,romfile=AMDGopDriver_8945.rom
hostpci2: 0000:c6:00.5,pcie=1
hostpci3: 0000:c6:00.6,pcie=1
```

Audio over 3.5 jack is working, will test for delays/crackling.

**Comment by SaintLenneth** [comment]
Hi @dextouu / @FabioEight , how do you guys find the AMD offline drivers ? I tried for to search for it for quite some time,  but no luck.

image

**Comment by dextouu** [comment]
> Hi @dextouu / @FabioEight , how do you guys find the AMD offline drivers ? I tried for to search for it for quite some time,  but no luck.
> 
> image
> 
> 
> 

I am French of origin, I go to a site that lists the drivers in my original language.

Here is the link:   https://www.touslesdrivers.com/index.php?v_page=23&v_code=78721

**Comment by dextouu** [comment]
> Update:
> 
> I was able to passthrough everything and get physical output, I had to add those devices as well:
> ```
> c6:00.5 Multimedia controller [0480]: Advanced Micro Devices, Inc. [AMD] ACP/ACP3X/ACP6x Audio Coprocessor [1022:15e2] (rev 63)
> 	Subsystem: Device [1f4c:b016]
> 	Kernel driver in use: vfio-pci
> 	Kernel modules: snd_pci_acp3x, snd_rn_pci_acp3x, snd_pci_acp5x, snd_pci_acp6x, snd_acp_pci, snd_rpl_pci_acp6x, snd_pci_ps, snd_sof_amd_renoir, snd_sof_amd_rembrandt, snd_sof_amd_vangogh, snd_sof_amd_acp63
> c6:00.6 Audio device [0403]: Advanced Micro Devices, Inc. [AMD] Family 17h/19h HD Audio Controller [1022:15e3]
> 	DeviceName: Realtek ALC256
> 	Subsystem: Device [1f4c:b016]
> 	Kernel driver in use: vfio-pci
> 	Kernel modules: snd_hda_intel
> ```
> 
> Current config:
> 
> ```
> hostpci0: 0000:c6:00.0,pcie=1,romfile=vbios_8945.bin,x-vga=1
> hostpci1: 0000:c6:00.1,pcie=1,romfile=AMDGopDriver_8945.rom
> hostpci2: 0000:c6:00.5,pcie=1
> hostpci3: 0000:c6:00.6,pcie=1
> ```
> 
> Audio over 3.5 jack is working, will test for delays/crackling.

Hello, how did you get the drivers for the co audio processor ? , I find nothing with the graphic drivers. That's why I removed it

**Comment by SaintLenneth** [comment]
@dextouu 
Thanks for that. I managed to install it now !

**Comment by FabioEight** [comment]
> > Update:
> > I was able to passthrough everything and get physical output, I had to add those devices as well:
> > ```
> > c6:00.5 Multimedia controller [0480]: Advanced Micro Devices, Inc. [AMD] ACP/ACP3X/ACP6x Audio Coprocessor [1022:15e2] (rev 63)
> > 	Subsystem: Device [1f4c:b016]
> > 	Kernel driver in use: vfio-pci
> > 	Kernel modules: snd_pci_acp3x, snd_rn_pci_acp3x, snd_pci_acp5x, snd_pci_acp6x, snd_acp_pci, snd_rpl_pci_acp6x, snd_pci_ps, snd_sof_amd_renoir, snd_sof_amd_rembrandt, snd_sof_amd_vangogh, snd_sof_amd_acp63
> > c6:00.6 Audio device [0403]: Advanced Micro Devices, Inc. [AMD] Family 17h/19h HD Audio Controller [1022:15e3]
> > 	DeviceName: Realtek ALC256
> > 	Subsystem: Device [1f4c:b016]
> > 	Kernel driver in use: vfio-pci
> > 	Kernel modules: snd_hda_intel
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Current config:
> > ```
> > hostpci0: 0000:c6:00.0,pcie=1,romfile=vbios_8945.bin,x-vga=1
> > hostpci1: 0000:c6:00.1,pcie=1,romfile=AMDGopDriver_8945.rom
> > hostpci2: 0000:c6:00.5,pcie=1
> > hostpci3: 0000:c6:00.6,pcie=1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Audio over 3.5 jack is working, will test for delays/crackling.
> 
> Hello, how did you get the drivers for the co audio processor ? , I find nothing with the graphic drivers. That's why I removed it

I just downloaded the drivers from AMD (offline) and then did Windows Update.

**Comment by antoninoromeo** [comment]
> Hello, I managed to get the graphics card working on Windows 11 including the audio. on windows 10, the graphics card gives me an error 43 on the graphics card. I added like 2 PCI ports, the third 3 is useless, I removed it. I added a capture below, to show in image. Capture d'écran 2024-09-25 192317
> 
> I also added the latest pack to extract the bios.bin (ubu), otherwise the extraction will not work on the latest models. I would also advise, for beginners or not, especially to add the "panic=10" parameter to grub, in case proxmox crashes, to avoid sudden shutdowns.

Hi @dextouu please can you explain how find the 8945HS bios for th UM890 pro, in the minisforum site is not available, i don't understand how to find the correct amdgop driver. If i undestood correctly via vibios.c i can extract bin bios file whil the gopdriver needs the minisforum 890 pro ufficial bios right? Many thanks to all. Have a nice day.

**Comment by dextouu** [comment]
> > Hello, I managed to get the graphics card working on Windows 11 including the audio. on windows 10, the graphics card gives me an error 43 on the graphics card. I added like 2 PCI ports, the third 3 is useless, I removed it. I added a capture below, to show in image. Capture d'écran 2024-09-25 192317
> > 
> > I also added the latest pack to extract the bios.bin (ubu), otherwise the extraction will not work on the latest models. I would also advise, for beginners or not, especially to add the "panic=10" parameter to grub, in case proxmox crashes, to avoid sudden shutdowns.
> 
> Hi @dextouu please can you explain how find the 8945HS bios for th UM890 pro, in the minisforum site is not available, i don't understand how to find the correct amdgop driver. If i undestood correctly via vibios.c i can extract bin bios file whil the gopdriver needs the minisforum 890 pro ufficial bios right? Many thanks to all. Have a nice day.


 Everything is available on the GitHub.

**Comment by antoninoromeo** [comment]
Hi aall @dextouu  pleas can you tell me i it's needed to use [RadeonResetBugFix](https://oomza.cutegay.software/inga-lovinde/RadeonResetBugFix/releases).  

If YES how to install it? on host (proxmox) ? on Ghuest (W11)? 
I have 890 pro sice 2 days and i'm preparing all the necessary. 
Many thanks.

**Comment by dextouu** [comment]
Hello, you install the fix on the VM (RadeonResetBugFix) .

**Comment by antoninoromeo** [comment]
> Hello, you install the fix on the VM (RadeonResetBugFix) . The fix is to avoid the error where you view the integrated graphics disable, In Windows 11 Device Manager .

Many  thanks @dextouu i'll tell you soon 👍  have a nice day

**Comment by antoninoromeo** [comment]
> Hello, I managed to get the graphics card working on Windows 11 including the audio. on windows 10, the graphics card gives me an error 43 on the graphics card. I added like 2 PCI ports, the third 3 is useless, I removed it. I added a capture below, to show in image. Capture d'écran 2024-09-25 192317
> 
> I also added the latest pack to extract the bios.bin (ubu), otherwise the extraction will not work on the latest models. I would also advise, for beginners or not, especially to add the "panic=10" parameter to grub, in case proxmox crashes, to avoid sudden shutdowns.

HI @FabioEight, @dextouu 

please, can you help me,  what should i do to have vfio-pci also on c5:00.5 Multimedia controller [0480]: and c5:00.6 Audio device [0403]: ?

my config is:

options vfio-pci ids=1002:1900,1002:1640
softdep radeon pre: vfio-pci
softdep amdgpu pre: vfio-pci
softdep snd_hda_intel pre: vfio-pci

lspci -nnk

c5:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix3 [1002:1900] (rev c4)
        Subsystem: Device [1f4c:b016]
        Kernel driver in use: **vfio-pci**
        Kernel modules: amdgpu
c5:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt Radeon High Definition Audio Controller [1002:1640]
        Subsystem: Device [1f4c:b016]
        Kernel driver in use: **vfio-pci**
        Kernel modules: snd_hda_intel
c5:00.2 Encryption controller [1080]: Advanced Micro Devices, Inc. [AMD] Family 19h (Model 74h) CCP/PSP 3.0 Device [1022:15c7]
        Subsystem: Device [1f4c:b016]
        Kernel driver in use: ccp
        Kernel modules: ccp
c5:00.3 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Device [1022:15b9]
        Subsystem: Device [1f4c:b016]
        Kernel driver in use: xhci_hcd
        Kernel modules: xhci_pci
c5:00.4 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Device [1022:15ba]
        Subsystem: Device [1f4c:b016]
        Kernel driver in use: xhci_hcd
        Kernel modules: xhci_pci
**c5:00.5** Multimedia controller [0480]: Advanced Micro Devices, Inc. [AMD] ACP/ACP3X/ACP6x Audio Coprocessor [1022:15e2] (rev 63)
        Subsystem: Device [1f4c:b016]
        Kernel driver in use: **snd_pci_ps**
        Kernel modules: snd_pci_acp3x, snd_rn_pci_acp3x, snd_pci_acp5x, snd_pci_acp6x, snd_acp_pci, snd_rpl_pci_acp6x, snd_pci_ps, snd_sof_amd_renoir, snd_sof_amd_rembrandt, snd_sof_amd_vangogh, snd_sof_amd_acp63
**c5:00.6** Audio device [0403]: Advanced Micro Devices, Inc. [AMD] Family 17h/19h HD Audio Controller [1022:15e3]
        DeviceName: Realtek ALC256
        Subsystem: Device [1f4c:b016]
        Kernel driver in use: **snd_hda_intel**
        Kernel modules: snd_hda_intel

many thanks, have a nice day.

**Comment by antoninoromeo** [comment]
> > > Update:
> > > I was able to passthrough everything and get physical output, I had to add those devices as well:
> > > ```
> > > c6:00.5 Multimedia controller [0480]: Advanced Micro Devices, Inc. [AMD] ACP/ACP3X/ACP6x Audio Coprocessor [1022:15e2] (rev 63)
> > > 	Subsystem: Device [1f4c:b016]
> > > 	Kernel driver in use: vfio-pci
> > > 	Kernel modules: snd_pci_acp3x, snd_rn_pci_acp3x, snd_pci_acp5x, snd_pci_acp6x, snd_acp_pci, snd_rpl_pci_acp6x, snd_pci_ps, snd_sof_amd_renoir, snd_sof_amd_rembrandt, snd_sof_amd_vangogh, snd_sof_amd_acp63
> > > c6:00.6 Audio device [0403]: Advanced Micro Devices, Inc. [AMD] Family 17h/19h HD Audio Controller [1022:15e3]
> > > 	DeviceName: Realtek ALC256
> > > 	Subsystem: Device [1f4c:b016]
> > > 	Kernel driver in use: vfio-pci
> > > 	Kernel modules: snd_hda_intel
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Current config:
> > > ```
> > > hostpci0: 0000:c6:00.0,pcie=1,romfile=vbios_8945.bin,x-vga=1
> > > hostpci1: 0000:c6:00.1,pcie=1,romfile=AMDGopDriver_8945.rom
> > > hostpci2: 0000:c6:00.5,pcie=1
> > > hostpci3: 0000:c6:00.6,pcie=1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Audio over 3.5 jack is working, will test for delays/crackling.
> > 
> > 
> > Hello, how did you get the drivers for the co audio processor ? , I find nothing with the graphic drivers. That's why I removed it
> 
> I just downloaded the drivers from AMD (offline) and then did Windows Update.


Hi @FabioEight , @dextouu 
please can you tell me if you resolved the problem with audio coprocessor as following?
image

I installed latest amd driver but no luck :(

this is my config:
options vfio-pci ids=1002:1900,1002:1640,1022:15e2,1022:15e3
softdep radeon pre: vfio-pci
softdep amdgpu pre: vfio-pci
softdep snd_hda_intel pre: vfio-pci
softdep snd_pci_ps  pre: vfio-pci

c5:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix3 [1002:1900] (rev c4)
        Subsystem: Device [1f4c:b016]
        Kernel driver in use: vfio-pci
        Kernel modules: amdgpu
c5:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt Radeon High Definition Audio Controller [1002:1640]
        Subsystem: Device [1f4c:b016]
        Kernel driver in use: vfio-pci
        Kernel modules: snd_hda_intel
c5:00.5 Multimedia controller [0480]: Advanced Micro Devices, Inc. [AMD] ACP/ACP3X/ACP6x Audio Coprocessor [1022:15e2] (rev 63)
        Subsystem: Device [1f4c:b016]
        Kernel driver in use: vfio-pci
        Kernel modules: snd_pci_acp3x, snd_rn_pci_acp3x, snd_pci_acp5x, snd_pci_acp6x, snd_acp_pci, snd_rpl_pci_acp6x, snd_pci_ps, snd_sof_amd_renoir, snd_sof_amd_rembrandt, snd_sof_amd_vangogh, snd_sof_amd_acp63
c5:00.6 Audio device [0403]: Advanced Micro Devices, Inc. [AMD] Family 17h/19h HD Audio Controller [1022:15e3]
        DeviceName: Realtek ALC256
        Subsystem: Device [1f4c:b016]
        Kernel driver in use: vfio-pci
        Kernel modules: snd_hda_intel

Many thanks, have a nice day.

**Comment by antoninoromeo** [comment]
HI all,
after windows update;

art VM 200: UPID:pve:00000775:00005E46:676866FB:qmstart:200:root@pam:
Dec 22 20:22:35 pve pvedaemon[1105]: <root@pam> starting task UPID:pve:00000775:00005E46:676866FB:qmstart:200:root@pam:
**Dec 22 20:22:35 pve pvedaemon[1909]: error writing '1' to '/sys/bus/pci/devices/0000:c5:00.0/reset': Inappropriate ioctl for device
Dec 22 20:22:35 pve pvedaemon[1909]: failed to reset PCI device '0000:c5:00.0', but trying to continue as not all devices need a reset**
Dec 22 20:22:35 pve systemd[1]: Created slice qemu.slice - Slice /qemu.
Dec 22 20:22:35 pve systemd[1]: Started 200.scope.
Dec 22 20:22:35 pve kernel: tap200i0: entered promiscuous mode
Dec 22 20:22:35 pve kernel: vmbr0: port 2(fwpr200p0) entered blocking state
Dec 22 20:22:35 pve kernel: vmbr0: port 2(fwpr200p0) entered disabled state
Dec 22 20:22:35 pve kernel: fwpr200p0: entered allmulticast mode
Dec 22 20:22:35 pve kernel: fwpr200p0: entered promiscuous mode
Dec 22 20:22:35 pve kernel: vmbr0: port 2(fwpr200p0) entered blocking state
Dec 22 20:22:35 pve kernel: vmbr0: port 2(fwpr200p0) entered forwarding state
Dec 22 20:22:35 pve kernel: fwbr200i0: port 1(fwln200i0) entered blocking state
Dec 22 20:22:35 pve kernel: fwbr200i0: port 1(fwln200i0) entered disabled state
Dec 22 20:22:35 pve kernel: fwln200i0: entered allmulticast mode
Dec 22 20:22:35 pve kernel: fwln200i0: entered promiscuous mode
Dec 22 20:22:35 pve kernel: fwbr200i0: port 1(fwln200i0) entered blocking state
Dec 22 20:22:35 pve kernel: fwbr200i0: port 1(fwln200i0) entered forwarding state
Dec 22 20:22:35 pve kernel: fwbr200i0: port 2(tap200i0) entered blocking state
Dec 22 20:22:35 pve kernel: fwbr200i0: port 2(tap200i0) entered disabled state
Dec 22 20:22:35 pve kernel: tap200i0: entered allmulticast mode
Dec 22 20:22:35 pve kernel: fwbr200i0: port 2(tap200i0) entered blocking state
Dec 22 20:22:35 pve kernel: fwbr200i0: port 2(tap200i0) entered forwarding state
Dec 22 20:22:36 pve kernel: vfio-pci 0000:c5:00.0: enabling device (0002 -> 0003)
Dec 22 20:22:36 pve kernel: vfio-pci 0000:c5:00.1: enabling device (0000 -> 0002)
Dec 22 20:22:36 pve kernel: vfio-pci 0000:c5:00.5: enabling device (0000 -> 0002)
Dec 22 20:22:36 pve kernel: vfio-pci 0000:c5:00.6: enabling device (0000 -> 0002)
Dec 22 20:22:36 pve pvedaemon[1909]: VM 200 started with PID 1930.
Dec 22 20:22:36 pve pvedaemon[1105]: <root@pam> end task UPID:pve:00000775:00005E46:676866FB:qmstart:200:root@pam: OK
Dec 22 20:22:39 pve pvedaemon[1104]: VM 200 qmp command failed - VM 200 qmp command 'guest-ping' failed - got timeout
Dec 22 20:23:01 pve kernel: kvm: vcpu 2: requested 15625 ns lapic timer period limited to 200000 ns
Dec 22 20:23:01 pve kernel: kvm: vcpu 6: requested 15625 ns lapic timer period limited to 200000 ns
Dec 22 20:23:01 pve kernel: kvm: vcpu 0: requested 15625 ns lapic timer period limited to 200000 ns
Dec 22 20:23:01 pve kernel: kvm: vcpu 5: requested 15625 ns lapic timer period limited to 200000 ns
Dec 22 20:23:01 pve kernel: kvm: vcpu 7: requested 15625 ns lapic timer period limited to 200000 ns
**Dec 22 20:23:01 pve QEMU[1930]: kvm: vfio: Cannot reset device 0000:c5:00.6, depends on group 20 which is not owned.
Dec 22 20:23:01 pve QEMU[1930]: kvm: vfio: Cannot reset device 0000:c5:00.5, depends on group 20 which is not owned.**


System hungs i had to stop manually proxmox and afted doesn't work anymore :(
can you tell me how should i do guest windows update?
Many thanks

**Comment by dextouu** [comment]
I don't use co - processor, I use sunshine or parsec for stream on the vm.I don't need the co - processor for that. I got the same error on the co-processor, no driver found. Have you installed the service that allows you to reset the AMD hardware?
I've never had this error like this, even after update.

**Comment by dextouu** [comment]
I don't use co - processor, I use sunshine or parsec for stream on the vm.I don't need the co - processor for that. I got the same error on the co-processor, no driver found. Have you installed the service that allows you to reset the AMD hardware?
I've never had this error like this, even after update.

**Comment by antoninoromeo** [comment]
> I don't use co - processor, I use sunshine or parsec for stream on the vm.I don't need the co - processor for that. I got the same error on the co-processor, no driver found. Have you installed the service that allows you to reset the AMD hardware? I've never had this error like this, even after update.

[ Hi @dextouu thanks for reply,
i should try to remove audio coprocessor from passtrow devices, another test that i should do is to blaocklist all the Kernel modules: snd_pci_acp3x, snd_rn_pci_acp3x, snd_pci_acp5x, snd_pci_acp6x, snd_acp_pci, snd_rpl_pci_acp6x, snd_pci_ps, snd_sof_amd_renoir, snd_sof_amd_rembrandt, snd_sof_amd_vangogh, snd_sof_amd_acp63

what do you think about it? 
Do you know if someone tried to passthrow AI corpocessor? 
IMG-20241225-WA0025
]
Have a nice day.

**Comment by Dyrkon** [comment]
Has anyone encountered graphical glitches after successful passthrough?

After I manager to get the gpu passed to the windows 11 and once I install drivers, the apps start glitching. From what I found, this might be caused by proxmox not being able to reset the gpus since they are scatered across iommu groups and I haven't managed to get them into one group.

**Pull request merged**
