### PR TITLE
Beelink SER7

### PR DESCRIPTION
**Pull request by jjyn0215**
Hi, Tested on Beelink SER7
Proxmox 8.2.5, Windows 11.
3840x2160 resolution, 120hz, with FreeSync Premium Pro HDR enabled.

화면 캡처 2024-09-21 015310

### CODE REVIEW

**Comment by levs21** [comment]
Hi, it try to pass trough 7840hs with M780 IGPU on my SER7 mini pc with  Proxmox 8.3.1  to WIN10 WM and after many attempts it is always crush so i need to hard reboot entire host  or simply won't start. Did you follow manual on Github exactly as it is? Can you share your wm config please. Any advice will be much appreciated.

**Comment by jjyn0215** [comment]
> Hi, it try to pass trough 7840hs with M780 IGPU on my SER7 mini pc with Proxmox 8.3.1 to WIN10 WM and after many attempts it is always crush so i need to hard reboot entire host or simply won't start. Did you follow manual on Github exactly as it is? Can you share your wm config please. Any advice will be much appreciated.

It was a few months ago so I'm not quite sure but did you passthrough built-in HD audio controller and audio coprocessor? should be X.00.1 and X.00.5. Because I have same memory with your question.

**Comment by levs21** [comment]
> It was a few months ago so I'm not quite sure but did you passthrough built-in HD audio controller and audio coprocessor? should be X.00.1 and X.00.5. Because I have same memory with your question.

I partially fixed it by removing c.00.1 audio controller and only c.00.0 which is my iGPU left and this allowed me to boot Win10 WM and install Vfio drivers,  I will work with audio later.. Next step in manual is to download offline AMD driver and I took the last one Adrenalin 24.12.1 for AMD Ryzen™ 7 7840HS but it stuck after initializing installation 100%. I guess some previous drivers may work better. As I understand you also use Ser7 minipc, can you check which exact AMD driver did you use to get it  install and work correctly?

**Comment by jjyn0215** [comment]
> I partially fixed it by removing c.00.1 audio controller and only c.00.0 which is my iGPU left and this allowed me to boot Win10 WM and install Vfio drivers, I will work with audio later.. Next step in manual is to download offline AMD driver and I took the last one Adrenalin 24.12.1 for AMD Ryzen™ 7 7840HS but it stuck after initializing installation 100%. I guess some previous drivers may work better. As I understand you also use Ser7 minipc, can you check which exact AMD driver did you use to get it install and work correctly?

mine was 24.8.1 but I think the latest driver should work, so check your settings agian if you can.

**Comment by levs21** [comment]
> mine was 24.8.1 but I think the latest driver should work, so check your settings agian if you can.

Everything is OK with 24.8.1 and I add audio controller and audio coprocessor too. Many thanks for your help!

**Pull request merged**
