### PR TITLE
Aoostar Gem12

### PR DESCRIPTION
**Pull request by fr3sh**
Tested with Aoostar Gem12

### CODE REVIEW

**Comment by isc30** [comment]
Great thanks!

**Comment by roger-** [comment]
I extracted AmdGopDrive.rom from the latest bios [here](https://aoostar.com/pages/drives-systems) (`GEM12 7840HS/8845HS [BIOS](04/22)`) and it doesn't match this one byte-for-byte. 

@fr3sh were you able to get pass through working? I'm trying to get it working for a Linux VM but no luck (driver crashes).

**Comment by fr3sh** [comment]
> I extracted AmdGopDrive.rom from the latest bios [here](https://aoostar.com/pages/drives-systems) (`GEM12 7840HS/8845HS [BIOS](04/22)`) and it doesn't match this one byte-for-byte.
> 
> @fr3sh were you able to get pass through working? I'm trying to get it working for a Linux VM but no luck (driver crashes).

yes form me it's working.

**Comment by fr3sh** [comment]
> Why thats only file in repo is 8845hs.dat no .bin?

If I remember that this is the only things that you need.

**Comment by smarticz** [comment]
> > Why thats only file in repo is 8845hs.dat no .bin?
> 
> If I remember that this is the only things that you need.

Do you change settings in bios? I have problem with 
error writing '1' to '/sys/bus/pci/devices/0000:c6:00.0/reset': Inappropriate ioctl for device
failed to reset PCI device '0000:c6:00.0', but trying to continue as not all devices need a reset
TASK ERROR: start failed: QEMU exited with code 1

**Comment by danni-cool** [comment]
I want to know if this rom file is also work fine for gem 12 (7840hs)?

**Pull request merged**
