### PR TITLE
AOOSTAR WTR PRO with Ryzen 7 5825U

### PR DESCRIPTION
**Pull request by purrowler**
AMDGopDriver & VBIOS for the new [AOOSTAR WTR PRO with AMD Ryzen 7 5825U](https://aoostar.com/collections/intel-pc-1/products/aoostar-wtr-pro-4-bay-90t-storage-amd-ryzen-7-5825u-nas-mini-pc-support-2-5-3-5-hdd-%E5%A4%8D%E5%88%B6?variant=49223254966570)

AOOSTAR does not provide the BIOS for download so i extracted it from the device using [AfuWin64](https://www.ami.com/bios-uefi-utilities/#aptiov)

For now i only tested it with a Windows 11 VM

VM config:

```
agent: 1
args: -cpu 'host,-hypervisor,kvm=off'
bios: ovmf
boot: order=ide0;ide2;net0
cores: 16
cpu: host
efidisk0: local-lvm:vm-100-disk-0,efitype=4m,pre-enrolled-keys=1,size=4M
hostpci0: 0000:04:00.0,pcie=1,romfile=vbios_5825U.bin,x-vga=1
hostpci1: 0000:04:00.1,pcie=1,romfile=AMDGopDriver-5825U.rom
ide0: local-lvm:vm-100-disk-1,discard=on,size=256G,ssd=1
ide2: local:iso/Win11_24H2_German_x64.iso,media=cdrom,size=5692008K
machine: pc-q35-9.0
memory: 16384
meta: creation-qemu=9.0.2,ctime=1730464345
name: Winodws11
net0: e1000=BC:24:11:C1:EF:10,bridge=vmbr0,firewall=1
numa: 0
ostype: win11
scsihw: virtio-scsi-single
smbios1: uuid=4960a08d-ab7a-4491-bbb9-822489f32737
sockets: 1
tpmstate0: local-lvm:vm-100-disk-2,size=4M,version=v2.0
usb0: host=046d:c534,usb3=1
vmgenid: 2de55296-9132-4a42-80aa-fa38045622bc
```

### CODE REVIEW

**Comment by ilGianfri** [comment]
I tried to use it with Windows Server 2022 but no luck.

Btw is it correct that the file vbios_5825U has .rom extension but in the vm config it says vbios_5825U.bin?

**Comment by purrowler** [comment]
You're right, i accidentally changed the extension to rom when copying it over to github.
I installed this [driver](https://www.amd.com/en/support/downloads/drivers.html/processors/ryzen/ryzen-5000-series/amd-ryzen-7-5825u.html).

**Comment by purrowler** [comment]
@ilGianfri 
> I tried to use it with Windows Server 2022 but no luck. What AMD driver did you use?



Just tested it with Windows Server 2022. Thats how i got it to work:
 
Disable Secure Boot  (When booting the VM press esc when proxmox logo appears -> `Device Manager` > `Secure Boot Configuration` > Uncheck the option `Attempt Secure Boot` -> esc back to the first screen -> `reset`

After the VM rebooted, open a command prompt disable driver validation using the commands `bcdedit /set nointegritychecks on` and `bcdedit /set testsigning on` and reboot the VM afterwards

[Download the Windows 10 installer of the driver](https://www.amd.com/en/support/downloads/drivers.html/processors/ryzen/ryzen-5000-series/amd-ryzen-7-5825u.html) and run it. 
It will tell you that you're using a unsupported OS but it extracts the installer files to C:\AMD.

Browse to `C:\AMD\AMD-Software-Installer\Packages\Drivers\Display\WT6A_INF` and open `u0407052.inf` with Notepad

Scroll down until you see the lines

```
[Manufacturer]
%ATI% = ATI.Mfg, NTamd64.10.0.1 .. 16299, NTamd64.10.0.1, NTamd64.6.0.1, NTamd64.6.1.1, NTamd64.6.2.1, NTamd64.6.3.1

[ATI.Mfg.NTamd64.10.0.1. .16299]
```
and delete everything after `%ATI% = ATI.Mfg, NTamd64` and `ATI.Mfg.NTamd64` so it looks like this:

```
[Manufacturer]
%ATI% = ATI.Mfg, NTamd64

[ATI.Mfg.NTamd64]
```
save and exit the file.

Open Device Manager, rightclick on `Microsoft Basic Display Adapter` and select `Update Drivers`

Select `Browse my computer for drivers` -> `Let me pick from a list of available drivers on my computer` 

Select `Have Disk`, browse `C:\AMD\AMD-Software-Installer\Packages\Drivers\Display\WT6A_INF\u0407052.inf` and select OK

Mark `AMD Radeon (TM) Graphics`, click on Next, accept all the unsigned driver prompts and after that it should be properly installed.

If you need the AMD control center, navigate to `C:\AMD\AMD-Software-Installer\Packages\Drivers\Display\WT6A_INF\B406619` and run `ccc2_install.exe` to install it.

Also don't forget to install the [RadeonResetBugFixService](https://github.com/inga-lovinde/RadeonResetBugFix) after that.

image

**Comment by ilGianfri** [comment]
@purrowler I was able to get it working following your guide. Thank you!

**Comment by purrowler** [comment]
@internethostage 


> What proxmox version are you running? qemu/kernel?

```
pve-manager/8.3.1/fb48e850ef9dde27 (running kernel: 6.8.12-5-pve)
QEMU emulator version 9.0.2 (pve-qemu-kvm_9.0.2-4) 
```
> Any bios settings you remember changing from the defaults?

AFAIK i only checked/changed those:
```
CPU Configuration > SVM Mode = Enabled
AMD CBS > NBIO Common Options > IOMMU = Enabled
AMD CBS > NBIO Common Options > GFX Configuration > iGPU Configuration = UMA_GAME_OPTIMIZED
```

> Did you follow all the steps from the readme or did you add something else? (for example on grub anything else than "quiet iommu=pt", same /etc/modprobe.d/vfio.conf and /etc/modules)

I followed the readme:


`lspci -nn | grep -e 'AMD/ATI'` result was: 
```
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Barcelo [1002:15e7] (rev c1)
04:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Renoir Radeon High Definition Audio Controller [1002:1637]

```
```
sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/GRUB_CMDLINE_LINUX_DEFAULT="quiet iommu=pt"/g' /etc/default/grub
update-grub
echo "vfio" >> /etc/modules
echo "vfio_iommu_type1" >> /etc/modules
echo "vfio_pci" >> /etc/modules
echo "vfio_virqfd" >> /etc/modules
echo "options vfio-pci ids=1002:15e7,1002:1637" >> /etc/modprobe.d/vfio.conf
echo "softdep radeon pre: vfio-pci" >> /etc/modprobe.d/vfio.conf
echo "softdep amdgpu pre: vfio-pci" >> /etc/modprobe.d/vfio.conf
echo "softdep snd_hda_intel pre: vfio-pci" >> /etc/modprobe.d/vfio.conf
update-initramfs -u -k all
shutdown -r now
```
`lspci -nnk` then correctly shows:
```
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Barcelo [1002:15e7] (rev c1)
        Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Barcelo [1002:0123]
        Kernel driver in use: vfio-pci
        Kernel modules: amdgpu
04:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Renoir Radeon High Definition Audio Controller [1002:1637]
        Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Renoir Radeon High Definition Audio Controller [1002:1637]
        Kernel driver in use: vfio-pci
        Kernel modules: snd_hda_intel
```
And connected display (correctly) shows to be stuck somewhere at the beginning of the boot process. In my case:
```
 Found volume group "pve" using metadata type lvm2
 24 logical volumes(s) in volume group "pve" now active
/sbin/fsck.xfs: XFS file system.
```

> Do you remember by chance the order of driver installation? For example install win11 without the passthrough, then when installed and virtio drivers installed, then do the passthrough and install drivers?

Mostly same as readme. Created VM (using UEFI insted of BIOS since it's Windows 11) , only installed windows, shutdown and then extracted and added the vbios to the config. After that i only installed VirtIO and AMD Driver. It didn't work so i went to hell and back (took me way to long since i had no idea what i was doing) to extract the `AMDGopDriver.rom`. After that i reinstalled the AMD Driver and the GPU appeared in taskmanager. Then i installed the RadeonResetBugFix, shut down the VM & set GPU as primary GPU.

> Any particular amd drivers version you installed? Current shows as Adrenalin 24.9.1 (WHQL), did you do full install or just drivers?

No, i just installed the one linked on the site. It's still the same version aswell. I did the full install.
AMD Software shows in case you want to compare versions:

image

> Did you/Do you have a monitor plugged in to the wtr pro? If you do, is it turned on?

Both and both. Using a Monitor and USB mouse & Keyboard and using no Monitor and RDP works fine.

Maybe you forgot to undo something you did from the previous passthrough? I think the best option (id you didn't do much customization) would be to backup your VMs/CTs and start from a fresh install of proxmox.

Also maybe the RDP Problem you saw is [this](https://answers.microsoft.com/en-us/windowsclient/forum/all/rdp-display-problems/1f3fda50-5bca-4c21-9ca7-00eb78661ac5)? Seems to be a Win11 24H2 bug.

**Comment by internethostage** [comment]
Thank you so much for your detailed reply.

I finally got it working, and I realized the issue. Its incredibly embarrassing 🤦‍♂️  but might help others so sharing here.

I was using the link on the repository home to download the bios'es

For example:
https://github.com/isc30/ryzen-7000-series-proxmox/blob/main/AMDGopDriver-5825U.rom
Instead of clicking on it, and then getting the raw link (correct)
https://github.com/isc30/ryzen-7000-series-proxmox/raw/refs/heads/main/AMDGopDriver-5825U.rom

Appreciate your time on getting all these details for me, mvp 🥳

**Comment by CeIestial** [comment]
Just for anyone trying this, the main recommended setting SeaBIOS does not work, at least for my case.
Using UEFI did not cause any issues on windows 11 install and enabled passthrough without hassle.

**Comment by pelMEN** [comment]
s anyone having issues with the machine stopping or restarting unpredictably?

**Comment by navossoc** [comment]
@purrowler How did you extract the AMDGopDriver?
I mean, I'm trying, but I just got a raw x64 PE file without any signatures... 
Your file have an extra header at the beginning and is signed.

I'm trying the [Beelink EQR5 BIOS FP656V507](https://dr.bee-link.cn/?dir=uploads%2FEQR%2FBios%2FEQR5):
```AMD GOP X64 Release Driver Rev.2.24.0.17.10.Mar 19 2024.02:19:42```

Your file have this version:
```AMD GOP X64 Release Driver Rev.2.18.0.17.10.May  4 2021.04:16:52```

**Pull request merged**
